/// Flutter icons VbaIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  VbaIcons
///      fonts:
///       - asset: fonts/VbaIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class VbaIcons {
  VbaIcons._();

  static const _kFontFam = 'VbaIcons';
  static const String? _kFontPkg = null;

  static const IconData settings = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData activity = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graph = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
